services:
  highloadsocialnetwork.webserver:
    image: ${DOCKER_REGISTRY-}highloadsocialnetworkwebserver
    build:
      context: ../
      dockerfile: HighloadSocialNetwork.WebServer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      DEV_AUTH_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQ0YmQwMWE2LWI5MDUtNDAwNy05NTA2LTE4MTcxNDEzYzFkNiIsImV4cCI6NDg4MzE0NjU1NH0.ZCFMCJT5Cb6RgzKVN-F6A5p3y-EBS-3Vgzl2VeQkRaA
      ConnectionStrings__DbUri: User Id=postgres;Password=1;Server=postgres;Port=5432;Database=highloadsocialnetwork_db;Pooling=true;Minimum Pool Size=1;Maximum Pool Size=100;SSL Mode=Allow;Include Error Detail=true
      ConnectionStrings__MasterDbUri: User Id=postgres;Password=1;Server=postgres;Port=5432;Database=postgres;Pooling=true;Minimum Pool Size=1;Maximum Pool Size=5;SSL Mode=Allow;Include Error Detail=true
      Auth__Jwt_SecretKey: povozatuvnvgytpaibdqfehgkxwakgfv
    ports:
      - 5000:80
    depends_on:
      - postgres
    networks:
      - hl-sn
  
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "1"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    networks:
      - hl-sn

networks:
  hl-sn:
    name: hl-sn-network
    external: false
    driver: bridge